# Generated by Django 3.2.23 on 2024-02-21 11:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posters', '0002_alter_poster_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poster',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, default=5, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
