# Generated by Django 3.2.23 on 2024-02-23 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posters', '0003_alter_poster_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poster',
            name='name',
            field=models.CharField(max_length=120),
        ),
    ]
