# Generated by Django 3.2.23 on 2024-02-11 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='description',
            new_name='remark',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='name',
            new_name='title',
        ),
    ]
