# Generated by Django 3.2.23 on 2024-02-11 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20240211_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='remark',
            new_name='review',
        ),
    ]
