# Generated by Django 3.2.23 on 2024-02-11 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_rename_remark_review_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review',
            new_name='content',
        ),
        migrations.AddField(
            model_name='review',
            name='user_displayed_name',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
