# Generated by Django 3.2.23 on 2024-02-11 21:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20240211_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='amended_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
    ]
