# Generated by Django 3.2.23 on 2024-02-23 23:47

import django.core.validators
from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('special_days_firstday', models.DateTimeField()),
                ('special_days_lastday', models.DateTimeField()),
                ('special_days_id', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)])),
            ],
            options={
                'verbose_name_plural': 'Special Days',
                'ordering': ['special_days_firstday'],
            },
        ),
        migrations.AddConstraint(
            model_name='specialdays',
            constraint=models.CheckConstraint(check=models.Q(('special_days_lastday__gte', django.db.models.expressions.F('special_days_firstday'))), name='check_date_range'),
        ),
        migrations.AddConstraint(
            model_name='specialdays',
            constraint=models.CheckConstraint(check=models.Q(('special_days_id__range', (0, 2))), name='special_days_id_within_range'),
        ),
    ]
