# Generated by Django 3.2.23 on 2024-02-21 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bag', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='specialdays',
            constraint=models.CheckConstraint(check=models.Q(('special_days_id__range', (0, 2))), name='special_days_id_within_range'),
        ),
    ]
