# Generated by Django 3.2.23 on 2024-02-18 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bag', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialdays',
            name='special_days_firstday',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='specialdays',
            name='special_days_lastday',
            field=models.DateTimeField(),
        ),
    ]
